env:
  es6: true
  node: true
  mocha: true
extends:
  - standard
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier

rules:
  "no-unused-vars": "off"
  "@typescript-eslint/no-unused-vars": "error"
  prettier/prettier:
    - error

